import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import {
  Image as ImageIcon,
  Sparkles,
  Download,
  Copy,
  Check,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Sliders,
  Bookmark,
  FileCode,
  AlertCircle,
  X,
} from 'lucide-react';
import { ToolLayout } from '../components/common/ToolLayout';
import { Button } from '../components/common/Button';
import { EmptyState } from '../components/common/EmptyState';
import { CreateForgeLoader } from '../components/common/CreateForgeLoader';
import { useLanguage } from '../context/LanguageContext';
import { useToast } from '../context/ToastContext';
import { aiService } from '../services/aiService';
import { SUPPORTED_ASPECT_RATIOS } from '../constants/aspectRatios';

export const ImageGeneratorPage = () => {
  const { t } = useLanguage();
  const { showToast } = useToast();
  const location = useLocation();

  const [prompt, setPrompt] = useState('');
  const [style, setStyle] = useState('Realistic');
  const [aspectRatio, setAspectRatio] = useState('1:1');
  const [additionalInstructions, setAdditionalInstructions] = useState('');

  // Advanced options
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [seed, setSeed] = useState('');
  const [negativePrompt, setNegativePrompt] = useState('');
  const [lighting, setLighting] = useState('Natural Studio');
  const [composition, setComposition] = useState('Cinematic Wide');
  const [quality, setQuality] = useState('medium');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [imageLoadError, setImageLoadError] = useState(false);

  // Handle incoming prompt from Article Generator or History
  useEffect(() => {
    if (location.state?.prompt) {
      setPrompt(location.state.prompt);
      if (location.state.style) setStyle(location.state.style);
      if (location.state.aspectRatio) setAspectRatio(location.state.aspectRatio);
      if (location.state.result) setResult(location.state.result);
      showToast('Loaded visual prompt into workspace.', 'info');
    }
  }, [location.state]);

  const styles = [
    { name: 'Realistic', icon: '📸' },
    { name: 'Cinematic', icon: '🎬' },
    { name: 'Illustration', icon: '🎨' },
    { name: 'Anime', icon: '✨' },
    { name: '3D', icon: '🧊' },
    { name: 'Digital Art', icon: '🖌️' },
    { name: 'Minimalist', icon: '◻️' },
    { name: 'Fantasy', icon: '🐉' },
    { name: 'Cyberpunk', icon: '🌆' },
    { name: 'Product', icon: '📦' },
  ];

  const handleGenerate = async (e, isRegen = false) => {
    if (e) e.preventDefault();
    if (!prompt.trim()) {
      setError('Please provide a prompt describing the visual.');
      return;
    }

    // CRITICAL: Immediately clear previous image and error state
    setResult(null);
    setError('');
    setImageLoadError(false);
    setIsSaved(false);
    setLoading(true);

    // If regenerating, use a new random seed unless user specifically locked one
    const currentSeed =
      isRegen && !seed
        ? Math.floor(Math.random() * 1000000)
        : seed
        ? parseInt(seed, 10)
        : undefined;

    try {
      const res = await aiService.generateImage({
        prompt: prompt.trim(),
        style,
        aspectRatio,
        advancedOptions: {
          additionalInstructions: additionalInstructions.trim(),
          lighting: lighting || undefined,
          composition: composition || undefined,
          negativePrompt: negativePrompt.trim() || undefined,
          quality: quality || 'medium',
          seed: currentSeed,
        },
      });

      const responseImage = res?.imageUrl || res?.data?.imageUrl;

      if (res?.success && responseImage) {
        setResult({
          ...(res.data || res),
          imageUrl: responseImage,
          style: res?.style || res?.data?.style || style,
          aspectRatio: res?.aspectRatio || res?.data?.aspectRatio || aspectRatio,
          revisedPrompt: res?.revisedPrompt || res?.data?.revisedPrompt,
          provider: res?.provider || res?.data?.provider || 'pollinations',
          model: res?.model || res?.data?.model || 'flux',
        });
        setImageLoadError(false);
        showToast('Visual successfully generated by CreateForge FLUX.', 'success');
      } else {
        setResult(null);
        setError("We couldn't retrieve a valid visual. Please try again.");
      }
    } catch (err) {
      setResult(null); // Ensure result remains empty on failure
      const customMsg =
        err?.response?.data?.message ||
        err?.response?.data?.error?.message ||
        err?.customMessage ||
        err?.message;
      setError(customMsg || 'We could not generate this image. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!result?.imageUrl) return;
    try {
      const today = new Date().toISOString().slice(0, 10).replace(/-/g, '');
      const slug = prompt
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '')
        .slice(0, 24);
      const filename = `createforge-ai-${slug || 'visual'}-${today}.png`;

      // Fetch blob to handle both remote URLs and data URIs cleanly
      const response = await fetch(result.imageUrl);
      const blob = await response.blob();
      const blobUrl = URL.createObjectURL(blob);

      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(blobUrl);

      showToast('Downloaded visual asset as PNG.', 'success');
    } catch {
      showToast('Could not download image. Opening in new tab...', 'info');
      window.open(result.imageUrl, '_blank');
    }
  };

  const handleCopyPrompt = () => {
    const textToCopy = result?.revisedPrompt || result?.prompt || prompt;
    navigator.clipboard.writeText(textToCopy);
    setCopiedPrompt(true);
    showToast('Copied generation prompt to clipboard.', 'success');
    setTimeout(() => setCopiedPrompt(false), 2000);
  };

  const handleCopyMarkdown = () => {
    if (!result?.imageUrl) return;
    const md = `![${prompt}](${result.imageUrl})`;
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    showToast('Copied Markdown embed code to clipboard.', 'success');
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleToggleSave = () => {
    setIsSaved(!isSaved);
    showToast(
      !isSaved
        ? 'Visual marked as favorite and saved to your library.'
        : 'Removed from favorites.',
      'info'
    );
  };

  const leftPane = (
    <form onSubmit={handleGenerate} className="space-y-4">
      {/* Prompt Input */}
      <div>
        <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
          {t('promptLabel')}
        </label>
        <textarea
          rows={4}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe your scene in detail... (e.g. A realistic red sports car parked on a modern city street at sunset)"
          disabled={loading}
          required
          className="w-full text-xs p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-indigo-500 shadow-xs resize-none"
        />
      </div>

      {/* Style Selector */}
      <div>
        <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
          {t('styleLabel')}
        </label>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-1.5">
          {styles.map((s) => (
            <button
              key={s.name}
              type="button"
              onClick={() => setStyle(s.name)}
              disabled={loading}
              className={`p-2 rounded-lg text-center transition-all flex flex-col items-center gap-1 border text-xs select-none ${
                style === s.name
                  ? 'bg-indigo-600 text-white font-semibold border-indigo-600 shadow-xs'
                  : 'bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
              }`}
            >
              <span className="text-sm">{s.icon}</span>
              <span className="text-[11px] truncate w-full">{s.name}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Aspect Ratio Selector */}
      <div>
        <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
          {t('aspectRatioLabel')}
        </label>
        <div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5">
          {SUPPORTED_ASPECT_RATIOS.map((ratio) => (
            <button
              key={ratio.id}
              type="button"
              onClick={() => setAspectRatio(ratio.id)}
              disabled={loading}
              className={`p-2 rounded-lg text-center transition-all border text-xs select-none ${
                aspectRatio === ratio.id
                  ? 'bg-indigo-600 text-white font-semibold border-indigo-600 shadow-xs'
                  : 'bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
              }`}
            >
              <span className="font-bold text-[11px] block">{ratio.label}</span>
              <span className="text-[9px] opacity-75 block truncate">{ratio.dimensions}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Collapsible Advanced Parameters */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-lg p-3 bg-slate-50/50 dark:bg-slate-900/40 space-y-2">
        <button
          type="button"
          onClick={() => setShowAdvanced(!showAdvanced)}
          className="w-full flex items-center justify-between text-xs font-medium text-slate-700 dark:text-slate-300"
        >
          <span className="flex items-center gap-1.5">
            <Sliders className="w-3.5 h-3.5 text-indigo-500" />
            <span>{t('advancedOptionsLabel')}</span>
          </span>
          {showAdvanced ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>

        {showAdvanced && (
          <div className="pt-2 space-y-3 animate-in fade-in">
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-400 mb-1">
                Seed (Optional integer for reproducibility)
              </label>
              <input
                type="number"
                value={seed}
                onChange={(e) => setSeed(e.target.value)}
                placeholder="Random seed (e.g. 42109)"
                disabled={loading}
                className="w-full text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg p-1.5 text-slate-900 dark:text-slate-100"
              />
            </div>

            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-400 mb-1">
                {t('negativePromptLabel')}
              </label>
              <input
                type="text"
                value={negativePrompt}
                onChange={(e) => setNegativePrompt(e.target.value)}
                placeholder={t('negativePromptPlaceholder')}
                disabled={loading}
                className="w-full text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg p-1.5 text-slate-900 dark:text-slate-100"
              />
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div>
                <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-400 mb-1">
                  {t('lightingLabel')}
                </label>
                <select
                  value={lighting}
                  onChange={(e) => setLighting(e.target.value)}
                  disabled={loading}
                  className="w-full text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg p-1.5 text-slate-900 dark:text-slate-100"
                >
                  <option value="Natural Studio">Natural Studio</option>
                  <option value="Dramatic Volumetric">Dramatic Volumetric</option>
                  <option value="Golden Hour">Golden Hour</option>
                  <option value="Cyberpunk Neon">Cyberpunk Neon</option>
                </select>
              </div>

              <div>
                <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-400 mb-1">
                  {t('compositionLabel')}
                </label>
                <select
                  value={composition}
                  onChange={(e) => setComposition(e.target.value)}
                  disabled={loading}
                  className="w-full text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg p-1.5 text-slate-900 dark:text-slate-100"
                >
                  <option value="Cinematic Wide">Cinematic Wide</option>
                  <option value="Macro Close-Up">Macro Close-Up</option>
                  <option value="Centered Isometric">Centered Isometric</option>
                  <option value="Top-Down Editorial">Top-Down Editorial</option>
                </select>
              </div>
            </div>
          </div>
        )}
      </div>

      <Button
        type="submit"
        loading={loading}
        disabled={loading}
        className="w-full shadow-sm"
        icon={Sparkles}
      >
        {loading ? '✦ Creating visual with FLUX...' : t('generateImageBtn')}
      </Button>
    </form>
  );

  const rightPane = (
    <div className="flex-1 flex flex-col justify-between space-y-4">
      {/* Inline Error Banner */}
      {error && (
        <div className="p-3.5 rounded-xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800/50 text-red-700 dark:text-red-300 text-xs flex items-center justify-between gap-2 animate-in fade-in">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0 text-red-500" />
            <span>{error}</span>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={(e) => handleGenerate(e, true)}
              className="text-xs font-semibold underline hover:no-underline text-red-700 dark:text-red-300"
            >
              Try Again
            </button>
            <button
              type="button"
              onClick={() => setError('')}
              className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      )}

      {/* Loading State */}
      {loading ? (
        <div className="flex-1 flex items-center justify-center p-8 rounded-xl bg-slate-50/50 dark:bg-[#0a0f1d]/40 border border-slate-200 dark:border-slate-800 min-h-[380px]">
          <CreateForgeLoader
            variant="image"
            aspectRatio={aspectRatio}
            customStages={[
              'Understanding your prompt',
              'Preparing visual composition',
              'FLUX is rendering your image',
              'Finishing visual details',
            ]}
          />
        </div>
      ) : result && result.imageUrl ? (
        /* Real AI Visual Display */
        <div className="space-y-4 flex-1 flex flex-col animate-in fade-in duration-300">
          {/* Header Controls */}
          <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-slate-200 dark:border-slate-800">
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 border border-indigo-200/50 dark:border-indigo-800/40">
                {result.style || style}
              </span>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400">
                {result.aspectRatio || aspectRatio}
              </span>
              <span className="text-[11px] text-slate-400 font-medium hidden sm:inline">
                FLUX Engine
              </span>
            </div>

            <div className="flex items-center gap-1.5 sm:gap-2 flex-wrap">
              <Button
                variant="outline"
                size="sm"
                icon={Bookmark}
                onClick={handleToggleSave}
                className={isSaved ? 'text-indigo-600 dark:text-indigo-400' : ''}
              >
                {isSaved ? 'Saved' : 'Save'}
              </Button>

              <Button
                variant="outline"
                size="sm"
                icon={copiedPrompt ? Check : Copy}
                onClick={handleCopyPrompt}
                title="Copy Prompt"
              >
                {copiedPrompt ? 'Copied' : 'Copy Prompt'}
              </Button>

              <Button
                variant="outline"
                size="sm"
                icon={copiedMarkdown ? Check : FileCode}
                onClick={handleCopyMarkdown}
                title="Copy Markdown"
              >
                {copiedMarkdown ? 'Copied' : 'Markdown'}
              </Button>

              <Button
                size="sm"
                icon={Download}
                onClick={handleDownload}
              >
                Download PNG
              </Button>

              <Button
                variant="secondary"
                size="sm"
                icon={RefreshCw}
                disabled={loading}
                onClick={(e) => handleGenerate(e, true)}
              >
                {t('regenerateBtn')}
              </Button>
            </div>
          </div>

          {/* Real AI Visual Display */}
          <div className="flex-1 flex items-center justify-center p-4 rounded-xl bg-slate-100/70 dark:bg-[#0c111c]/60 border border-slate-200 dark:border-slate-800 overflow-hidden shadow-inner min-h-[340px]">
            {imageLoadError ? (
              <div className="flex flex-col items-center justify-center gap-3 py-8 text-center">
                <div className="w-12 h-12 rounded-xl bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800/40 flex items-center justify-center">
                  <ImageIcon className="w-6 h-6 text-red-400" />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                    Image couldn't be displayed
                  </p>
                  <p className="text-xs text-slate-500">
                    The generated visual may have failed to render. Try regenerating.
                  </p>
                </div>
              </div>
            ) : (
              <img
                src={result.imageUrl}
                alt={prompt}
                className="max-h-[480px] w-auto max-w-full rounded-lg object-contain shadow-lg transition-all duration-300"
                onError={() => setImageLoadError(true)}
              />
            )}
          </div>

          {/* Prompt caption */}
          <div className="flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
            <p className="italic truncate max-w-[80%]">
              "{prompt}"
            </p>
            <span className="text-[11px] text-slate-400">
              CreateForge AI • FLUX
            </span>
          </div>
        </div>
      ) : (
        /* Empty State */
        <div className="flex-1 flex items-center justify-center min-h-[340px]">
          <EmptyState
            icon={ImageIcon}
            title={t('emptyStateImageTitle') || 'Your generated visual starts here'}
            description={
              t('emptyStateImageDesc') ||
              'Enter a detailed prompt, choose an artistic style and aspect ratio, then click Generate to create a real visual powered by FLUX.'
            }
          />
        </div>
      )}
    </div>
  );

  return (
    <ToolLayout
      title={t('imageGenTitle') || 'FLUX Image Generator'}
      subtitle={
        t('imageGenSubtitle') ||
        'Synthesize high-fidelity visual assets, illustrations, and photorealistic imagery with FLUX.'
      }
      leftPane={leftPane}
      rightPane={rightPane}
    />
  );
};
